---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- My First Group:
    - My First Service:
        href: http://localhost/
        description: Homepage is awesome

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is ðŸ˜Ž
- Top Services:
    - Proxmox:
        icon: proxmox.png # icons found here https://github.com/walkxcode/dashboard-icons
        href: https://192.168.0.15:8006
        description: Proxmox VE
    - PiHole:
        icon: pi-hole.svg # icons found here https://github.com/walkxcode/dashboard-icons
        href: http://192.168.60.10/admin
        description: Server 1
    - Cowboy:
        icon: mdi-account-cowboy-hat-#FF0000 # icons found here https://pictogrammers.com/library/mdi/
        href: https://localhost/
        description: giddyup service
    - McDonaldâ€™s:
        icon: si-mcdonalds-#FFD700 # icons found here https://simpleicons.org/
        href: https://www.mcdonalds.com/
        description: homepage
    # ^^^ add this block
